name: Build Artifact

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        type: choice
        required: true
        default: 'ubuntu-latest'
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest

jobs:
  Build:
    name: Build (${{ inputs.os }})
    runs-on: ${{ inputs.os }}
    steps:
      - name: 'Checkout branch'
        uses: actions/checkout@v3

      - name: 'Set up Graal'
        uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.0'
          java-version: '17'
          components: 'native-image'
          cache: 'maven'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build & Test'
        run: ./mvnw package -Pnative

      - name: 'Upload artifact'
        uses: actions/upload-artifact@v2
        with:
          name: artifacts for ${{ inputs.os }}
          path: target/app

